basePath: /
definitions:
  model.Address:
    properties:
      city:
        type: string
      country:
        type: string
      postalCode:
        type: string
      state_or_province:
        type: string
      street:
        type: string
    type: object
  model.Hotel:
    properties:
      address:
        $ref: '#/definitions/model.Address'
      id:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
  server.ErrorResponse:
    description: Error response
    properties:
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for CassandraTest.
  title: CassandraTest API
  version: "1.0"
paths:
  /hotel/{id}:
    get:
      description: get hotel by id
      parameters:
      - description: Hotel ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Hotel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      summary: Get hotel by id
      tags:
      - hotels
  /hotels:
    get:
      description: get hotels
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Hotel'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      summary: List hotels
      tags:
      - hotels
swagger: "2.0"
